version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
